### Get all contacts
GET http://localhost:8080/contacts

### Get contact by ID
GET http://localhost:8080/contacts/6a9ef77aaf6c407c594f2093

### Create contact
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "Joana",
  "lastName": "Teye",
  "email": "joanateye@test.com",
  "favoriteColor": "Blue",
  "birthday": "1995-05-15"
}

### Update contact
PUT http://localhost:8080/contacts/6aaa0e750e58df1784ca2cfa HTTP/1.1
Content-Type: application/json

{
  "firstName": "Joana",
  "lastName": "Teye",
  "email": "joanateye@gmail.com",
  "favoriteColor": "Green",
  "birthday": "1995-05-15"
}

### Delete contact
DELETE http://localhost:8080/contacts/6aaa0e750e58df1784ca2cfa HTTP/1.1